# -*- coding: utf-8 -*-
"""Optional_Peer_Graded_Assignment.jupyterlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAoKByu1-2vxd6ZStWbnTNmi1dyLnXJn

<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkST0151ENSkillsNetwork20531532-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

#### Import the required libraries we need for the lab.
"""

import piplite
await piplite.install(['numpy'],['pandas'])
await piplite.install(['seaborn'])

import pandas as pd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as pyplot
import scipy.stats
import statsmodels.api as sm
from statsmodels.formula.api import ols

"""#### Read the dataset in the csv file from the URL

"""

from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
resp = await fetch(URL)
boston_url = io.BytesIO((await resp.arrayBuffer()).to_py())

boston_df=pd.read_csv(boston_url)

"""#### Add your code below following the instructions given in the course to complete the peer graded assignment

# TASK 2
#### Generate Descriptive Statistics and Visualizations

##### "Median value of owner-occupied homes" represented by a boxplot
"""

boston_df.head()

boston_df['MEDV'].mean()

ax = sns.boxplot(y="MEDV" , data=boston_df)
ax.set_title("Box plot for median owner-occupied homes")
pyplot.show()

"""##### Provide a  bar plot for the Charles river variable"""

ax = sns.countplot(x="CHAS", data=boston_df)
ax.set_title("Bar plot for Charles variable")
pyplot.show()

"""##### Provide a boxplot for the MEDV variable vs the AGE variable"""

boston_df.loc[(boston_df['AGE'] <= 35), 'AGE_Group'] = '35 years and younger'
boston_df.loc[(boston_df['AGE'] > 35) & (boston_df['AGE'] < 70), 'AGE_Group'] = 'between 35 and 70 years'
boston_df.loc[(boston_df['AGE'] >= 70), 'AGE_Group'] = '70 years and older'

ax = sns.boxplot(x='MEDV', y="AGE_Group" , hue="AGE_Group" , data=boston_df)
ax.set_title("Box plot of MEDV vs AGE")
pyplot.show()

"""##### Provide a scatter plot to show the relationship between Nitric oxide concentrations and the proportion of non-retail business acres per town. What can you say about the relationship?"""

ax = sns.scatterplot(x='NOX', y='INDUS', data=boston_df)
pyplot.show()

"""We can see that there is a linear relationship between the values at the bottom-left section of the scatter plot. And this indicates a strong relation between low Nitric oxide concentration and low proportion of non-retail business acres per town.

Also we can notice that a higher level of non-retail business acres per town, it produces a higher concentration of Nitric oxide.

##### Create a histogram for the pupil to teacher ratio variable
"""

sns.catplot(x='PTRATIO', kind='count', data=boston_df)
pyplot.show()

"""# TASK 3
#### Use Statistics analysis

##### Is there a significant difference in median value of houses bounded by the Charles river or not?

Following hypothesis:

    'The difference between the median value houses bounded and not bounded by the Charles River is very high'
"""

boston_df.loc[(boston_df['CHAS'] == 0), 'CHAS_T'] = 'FAR'
boston_df.loc[(boston_df['CHAS'] == 1), 'CHAS_T'] = 'NEAR'
boston_df.head(5)

scipy.stats.ttest_ind(boston_df[boston_df['CHAS_T'] == 'FAR']['MEDV'],
                      boston_df[boston_df['CHAS_T'] == 'NEAR']['MEDV'], equal_var = True)

"""Since the p-value given is less than 0.05, this means that there is not a statistical difference in median value betwenn houses near the Charles River and houses being far away

##### Is there a difference in Median values of houses (MEDV) for each proportion of owner occupied units built prior to 1940 (AGE)?

Let's consider two follwing hypothesis

1. A null Hypotesis: There isn't statistical difference in Median values of houses (MEDV) for each proportion of owner occpied units built prior to 1940

2. A second Hypothesis: There is statistical difference in Median values of houses (MEDV) for each proportion of owner occpied units built prior to 1940
"""

boston_df.loc[(boston_df['AGE'] <= 35), 'AGE_Group'] = '35 years and younger'
boston_df.loc[(boston_df['AGE'] > 35) & (boston_df['AGE'] < 70), 'AGE_Group'] = 'between 35 and 70 years'
boston_df.loc[(boston_df['AGE'] >= 70), 'AGE_Group'] = '70 years and older'

from statsmodels.formula.api import ols
lm = ols('MEDV ~ AGE_Group', data = boston_df).fit()
table= sm.stats.anova_lm(lm)
print(table)

"""Since the p-value given is less than 0.05, we cannot accept the Null Hypothesis --> Therefore, there is statistical difference in Median values of houses (MEDV) for each proportion of owner occpied units built prior to 1940

##### Can we conclude that there is no relationship between Nitric oxide concentrations and proportion of non-retail business acres per town?
"""

scipy.stats.pearsonr(boston_df['NOX'], boston_df['INDUS'])

"""The Pearson Coefficient is 0.76365 and p-value less than 0.05, therefore the Null Hypothesis is not valid as there is a positive correlation between Nitric oxide concentration and proportion of non-retail business acres per town

##### What is the impact of an additional weighted distance  to the five Boston employment centres on the median value of owner occupied homes?
"""

## X is the input variables (or independent variables)
X = boston_df['DIS']
## y is the target/dependent variable
y = boston_df['MEDV']
## add an intercept (beta_0) to our model
X = sm.add_constant(X)

model = sm.OLS(y, X).fit()
predictions = model.predict(X)

# Print out the statistics
model.summary()

"""Since the coef DIS is 1.0916, it does indicate that an additional weighted distance of 5 employment centers in Boston it would increace of 1.0916 to the median value of owner occupied homes."""

